### ISSUE TITLE
auto width input

### ISSUE THREAD

**Issue by aufula** [aufula/aufula.github.io#2]
```jsx
<span className="btxt">
  <span>{title}</span>
  <input
    spellCheck={false}
    onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
      onChange(e.target.value);
    }}
    value={title}
  />
</span>
```

```scss
  .btxt {
    background: transparent;
    font-size: inherit;
    border: none;
    outline: none;
    position: relative;

    span {
      visibility: hidden;
    }
    input {
      background: transparent;
      font: inherit;
      border: none;
      top: 0;
      left: 0;
      padding: inherit;
      position: absolute;
      text-align: inherit;
      line-height: inherit;
      width: 100%;
      display: inherit;
      outline: 0;
    }
  }

```

原理： input的字号、宽高等，都和平级的span一样。这样利用react，state的更新，让span元素动态把容器撑开，input 100%宽即可
