### ISSUE TITLE
background grid

### ISSUE THREAD

**Issue by aufula** [aufula/aufula.github.io#3]
```css
.bg-grid{
background-color: transparent;
    background-image:       linear-gradient(0deg, transparent 24%, rgba(0, 0, 0, .05) 25%, rgba(0, 0, 0, .05) 26%, transparent 27%, transparent 74%, rgba(0, 0, 0, .05) 75%, rgba(0, 0, 0, .05) 76%, transparent 77%, transparent), linear-gradient(90deg, transparent 24%, rgba(0, 0, 0, .05) 25%, rgba(0, 0, 0, .05) 26%, transparent 27%, transparent 74%, rgba(0, 0, 0, .05) 75%, rgba(0, 0, 0, .05) 76%, transparent 77%, transparent);
  height:100%;
  background-size:50px 50px;
}
```

![image](https://user-images.githubusercontent.com/544442/47700063-08ec5300-dc50-11e8-91e0-29ffee79dc22.png)
